name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

#permissions:
#  contents: read

jobs:
  build:

    runs-on: ubuntu-22.04

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

#      - name: Build with Gradle and Make Test Report
#        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
#        with:
#          arguments: build jacocoTestReport

      - name: Run tests and build JaCoCo report
        run: ./gradlew test

      - name: Upload test report
        uses: actions/upload-artifact@v3.1.1
        with:
          name: TestReport
          path: ./tests/build/reports/tests/test/*

      - name: Upload JaCoCo coverage report as workflow artefact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: JacocoReport
          path: ./tests/build/reports/jacoco/test/html/*

      - name: Build with gradle wrapper
        run: ./gradlew desktop:dist

      - name: Upload JAR
        uses: actions/upload-artifact@v3.1.1
        with:
          name: PiazzaPanic.jar
          path: ./desktop/build/libs/desktop-1.0.jar

      - name: Upload Checkstyle report
        uses: actions/upload-artifact@v3.1.1
        with:
          name: CheckstyleReport
          path: ./*
