name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-22.04

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Run tests and build JaCoCo report
        run: ./gradlew test

      - name: Upload test report
        uses: actions/upload-artifact@v3.1.1
        with:
          name: TestReport
          path: ./tests/build/reports/tests/test/*

      - name: Upload JaCoCo coverage report as workflow artefact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: JacocoReport
          path: ./tests/build/reports/jacoco/test/html/*

      - name: Build with gradle wrapper
        run: ./gradlew desktop:dist

      - name: Upload JAR
        uses: actions/upload-artifact@v3.1.1
        with:
          name: PiazzaPanic.jar
          path: ./desktop/build/libs/Piazza-Panic-0.1.jar

      - name: Run checkstyle report on Core
        run: ./gradlew core:checkstyleMain

      - name: Upload Checkstyle report
        uses: actions/upload-artifact@v3.1.1
        with:
          name: CheckstyleReportCore
          path: ./build/reports/checkstyle.html

  macos-build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

#      - name: Build project
#        run: ./gradlew desktop:dist
      - name: Build with gradle wrapper
        run: ./gradlew desktop:dist

      - name: Create executable
        env:
          MACOS_DEVID_APP_CERT: ${{ secrets.MACOS_DEVID_APP_CERT }}
          MACOS_DEVID_APP_CERT_PWD: ${{ secrets.MACOS_DEVID_APP_CERT_PWD }}
          MACOS_DEVID_INS_CERT: ${{ secrets.MACOS_DEVID_INS_CERT }}
          MACOS_DEVID_INS_CERT_PWD: ${{ secrets.MACOS_DEVID_INS_CERT_PWD }}
        run: |
          echo $MACOS_DEVID_APP_CERT | base64 --decode > app_cert.p12
          echo $MACOS_DEVID_INS_CERT | base64 --decode > ins_cert.p12
          security import app_cert.p12 -P $MACOS_DEVID_APP_CERT_PWD
#          stop here
#          security import ins_cert.p12 -P $MACOS_DEVID_INS_CERT_PWD
#          mkdir exe_gen
#          cd exe_gen
#          cp ../assets/icon.icns ./
#          cp ../desktop/build/libs/Piazza-Panic-0.1.jar ./
#          jpackage --input ./ --name 'Piazza Panic' --main-jar Piazza-Panic-0.1.jar --type pkg --icon icon.icns --java-options '-XstartOnFirstThread' --mac-sign --mac-signing-key-user-name "Andrew Palombo"

#      - name: Create executable
#        run: |
#          mkdir exegen
#          cd exegen
#          cp ../assets/icon.icns ./
#          cp ../desktop/build/libs/Piazza-Panic-0.1.jar ./
#          jpackage --input ./ --name 'Piazza Panic' --main-jar Piazza-Panic-0.1.jar --type pkg --icon icon.icns --java-options '-XstartOnFirstThread'

      - name: Upload executable
        uses: actions/upload-artifact@v3.1.1
        with:
          name: PiazzaPanic
          path: ./exegen/Piazza Panic-1.0.pkg